// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = (function(flowee) {
    var e, me;
    flowee.auth = me = {};
    me.public_urls = {};
    me.ignore = function(url, method) {
      if (me.public_urls[url] == null) {
        me.public_urls[url] = {
          methods: {}
        };
      }
      return me.public_urls[url].methods[(method != null ? method : "get")] = true;
    };
    me.shouldignore = function(url, method) {
      if ((flowee.auth.public_urls[url] != null) && (flowee.auth.public_urls[url].methods[method.toLowerCase()] != null)) {
        return true;
      } else {
        return false;
      }
    };
    flowee.on('start', function(flowee) {
      var method, methods, path, ref, resource;
      ref = flowee.model.paths;
      for (path in ref) {
        methods = ref[path];
        for (method in methods) {
          resource = methods[method];
          if ((resource["public"] != null) && resource["public"]) {
            me.ignore(path, method);
          }
        }
      }
      if (flowee.verbosity > 1) {
        return console.log("public urls: " + JSON.stringify(me.public_urls, null, 2));
      }
    });
    me.getuser = function(opts, cb) {
      if (opts != null) {
        if (flowee.verbosity > 1) {
          console.log("requesting user with args: " + JSON.stringify(opts));
        }
        return flowee.request("find", {
          type: "user",
          payload: opts
        }).then(function(result) {
          var ref;
          if (flowee.verbosity > 1) {
            console.dir(result);
          }
          return cb((((ref = result.payload) != null ? ref.length : void 0) ? result.payload[0] : void 0));
        })["catch"](function() {
          return cb();
        });
      } else {
        return cb();
      }
    };
    try {
      require('./src/passport.strategy.apitoken')(flowee);
    } catch (_error) {
      e = _error;
      console.warn("flowee-auth: use 'npm install passport passport-accesstoken' for POST form authentication");
    }
    try {
      require('./src/passport.strategy.local')(flowee);
    } catch (_error) {
      e = _error;
      console.warn("flowee-auth: use 'npm install express-session body-parser passport passport-local' for POST form authentication");
    }
    return me;
  }).bind({});

}).call(this);
